/*
 * generated by Xtext 2.25.0
 */
package event.driven.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import event.driven.SceneDlRuntimeModule;
import event.driven.SceneDlStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SceneDlIdeSetup extends SceneDlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SceneDlRuntimeModule(), new SceneDlIdeModule()));
	}
	
}
