/**
 * generated by Xtext 2.25.0
 */
package event.driven.sceneDl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link event.driven.sceneDl.Contain#isMany <em>Many</em>}</li>
 *   <li>{@link event.driven.sceneDl.Contain#getName <em>Name</em>}</li>
 *   <li>{@link event.driven.sceneDl.Contain#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see event.driven.sceneDl.SceneDlPackage#getContain()
 * @model
 * @generated
 */
public interface Contain extends EObject
{
  /**
   * Returns the value of the '<em><b>Many</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Many</em>' attribute.
   * @see #setMany(boolean)
   * @see event.driven.sceneDl.SceneDlPackage#getContain_Many()
   * @model
   * @generated
   */
  boolean isMany();

  /**
   * Sets the value of the '{@link event.driven.sceneDl.Contain#isMany <em>Many</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Many</em>' attribute.
   * @see #isMany()
   * @generated
   */
  void setMany(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see event.driven.sceneDl.SceneDlPackage#getContain_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link event.driven.sceneDl.Contain#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(DynamicEntity)
   * @see event.driven.sceneDl.SceneDlPackage#getContain_Type()
   * @model
   * @generated
   */
  DynamicEntity getType();

  /**
   * Sets the value of the '{@link event.driven.sceneDl.Contain#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(DynamicEntity value);

} // Contain
