/**
 * generated by Xtext 2.25.0
 */
package event.driven.sceneDl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dynamic Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see event.driven.sceneDl.SceneDlPackage#getDynamicEntity()
 * @model
 * @generated
 */
public interface DynamicEntity extends Element
{
} // DynamicEntity
