/**
 * generated by Xtext 2.25.0
 */
package event.driven.sceneDl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link event.driven.sceneDl.Element#getType <em>Type</em>}</li>
 *   <li>{@link event.driven.sceneDl.Element#getName <em>Name</em>}</li>
 *   <li>{@link event.driven.sceneDl.Element#getKey <em>Key</em>}</li>
 *   <li>{@link event.driven.sceneDl.Element#getIsA <em>Is A</em>}</li>
 *   <li>{@link event.driven.sceneDl.Element#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see event.driven.sceneDl.SceneDlPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see event.driven.sceneDl.SceneDlPackage#getElement_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link event.driven.sceneDl.Element#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see event.driven.sceneDl.SceneDlPackage#getElement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link event.driven.sceneDl.Element#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' reference.
   * @see #setKey(Attribute)
   * @see event.driven.sceneDl.SceneDlPackage#getElement_Key()
   * @model
   * @generated
   */
  Attribute getKey();

  /**
   * Sets the value of the '{@link event.driven.sceneDl.Element#getKey <em>Key</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' reference.
   * @see #getKey()
   * @generated
   */
  void setKey(Attribute value);

  /**
   * Returns the value of the '<em><b>Is A</b></em>' reference list.
   * The list contents are of type {@link event.driven.sceneDl.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is A</em>' reference list.
   * @see event.driven.sceneDl.SceneDlPackage#getElement_IsA()
   * @model
   * @generated
   */
  EList<Element> getIsA();

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link event.driven.sceneDl.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see event.driven.sceneDl.SceneDlPackage#getElement_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // Element
