/**
 * generated by Xtext 2.25.0
 */
package event.driven.sceneDl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Position Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link event.driven.sceneDl.PositionAttribute#getX <em>X</em>}</li>
 *   <li>{@link event.driven.sceneDl.PositionAttribute#getY <em>Y</em>}</li>
 * </ul>
 *
 * @see event.driven.sceneDl.SceneDlPackage#getPositionAttribute()
 * @model
 * @generated
 */
public interface PositionAttribute extends Attribute
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see event.driven.sceneDl.SceneDlPackage#getPositionAttribute_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link event.driven.sceneDl.PositionAttribute#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see event.driven.sceneDl.SceneDlPackage#getPositionAttribute_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link event.driven.sceneDl.PositionAttribute#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

} // PositionAttribute
