/**
 * generated by Xtext 2.25.0
 */
package event.driven.sceneDl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Regular Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link event.driven.sceneDl.RegularAttribute#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see event.driven.sceneDl.SceneDlPackage#getRegularAttribute()
 * @model
 * @generated
 */
public interface RegularAttribute extends Attribute
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute list.
   * @see event.driven.sceneDl.SceneDlPackage#getRegularAttribute_Value()
   * @model unique="false"
   * @generated
   */
  EList<String> getValue();

} // RegularAttribute
