/**
 * generated by Xtext 2.25.0
 */
package event.driven.sceneDl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Static Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link event.driven.sceneDl.StaticEntity#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @see event.driven.sceneDl.SceneDlPackage#getStaticEntity()
 * @model
 * @generated
 */
public interface StaticEntity extends Element
{
  /**
   * Returns the value of the '<em><b>Features</b></em>' reference list.
   * The list contents are of type {@link event.driven.sceneDl.DynamicEntity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' reference list.
   * @see event.driven.sceneDl.SceneDlPackage#getStaticEntity_Features()
   * @model
   * @generated
   */
  EList<DynamicEntity> getFeatures();

} // StaticEntity
