/**
 * generated by Xtext 2.25.0
 */
package event.driven.tests;

/* @ExtendWith(/* name is null */)
@InjectWith(/* name is null */)
 */public class SceneDlParsingTest {
  /* @Inject
   */private /* ParseHelper<Scene> */Object parseHelper;
  
  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assertions is undefined"
      + "\nThe method or field Assertions is undefined"
      + "\nThe field SceneDlParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nassertTrue cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
