/*
 * generated by Xtext 2.25.0
 */
package event.driven;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SceneDlStandaloneSetup extends SceneDlStandaloneSetupGenerated {

	public static void doSetup() {
		new SceneDlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
