/*
 * generated by Xtext 2.25.0
 */
package event.driven.ui.tests;

import com.google.inject.Injector;
import event.driven.scene.dl.ui.internal.DlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SceneDlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DlActivator.getInstance().getInjector("event.driven.SceneDl");
	}

}
