/*
 * generated by Xtext 2.25.0
 */
package event.driven.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSceneDlValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(event.driven.sceneDl.SceneDlPackage.eINSTANCE);
		return result;
	}
}
