/*
 * generated by Xtext 2.25.0
 */
package event.driven.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSceneDlScopeProvider extends DelegatingScopeProvider {
}
