/**
 * generated by Xtext 2.25.0
 */
package event.driven.sceneDl.impl;

import event.driven.sceneDl.DynamicEntity;
import event.driven.sceneDl.SceneDlPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dynamic Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DynamicEntityImpl extends ElementImpl implements DynamicEntity
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DynamicEntityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SceneDlPackage.Literals.DYNAMIC_ENTITY;
  }

} //DynamicEntityImpl
