/*
 * generated by Xtext 2.25.0
 */
package event.driven.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SceneDlUiModule extends AbstractSceneDlUiModule {

	public SceneDlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
